name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  actions: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Determine Tag Version
      id: tag_version
      run: |
        TAG_NAME=$(git describe --tags --abbrev=0)
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "Determined tag version: $TAG_NAME"

    - name: Create or Get Release
      id: release
      run: |
        RESPONSE=$(curl -s -o response.txt -w "%{http_code}" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"$TAG_NAME\", \"body\": \"Automated release for version $TAG_NAME\", \"draft\": false, \"prerelease\": false}" \
        https://api.github.com/repos/irmo-de/9UnBot/releases)
        
        if [ "$(cat response.txt)" = "201" ]; then
          echo "Release created successfully."
        elif [ "$(cat response.txt)" = "422" ]; then
          echo "Release already exists."
        else
          echo "Unexpected response: $(cat response.txt)"
          exit 1
        fi

        RELEASE_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/irmo-de/9UnBot/releases/tags/$TAG_NAME" | jq -r .upload_url)
        UPLOAD_URL="${RELEASE_URL%\{*}"
        echo "::set-output name=upload_url::$UPLOAD_URL"

    - name: Upload APK to the Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}?name=app-debug.apk
        asset_path: ./app/build/outputs/apk/debug/app-debug.apk
        asset_name: app-debug.apk
        asset_content_type: application/vnd.android.package-archive
