name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: List APK files
      run: ls -l ./app/build/outputs/apk/debug/

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Get Release Information for v0.1.0
      id: get_release_info
      run: |
        RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/irmo-de/9UnBot/releases/tags/v0.1.0)
        UPLOAD_URL=$(echo $RELEASE_INFO | jq -r .upload_url | sed 's/{?name,label}//')
        echo "Upload URL is $UPLOAD_URL"
        echo "::set-output name=upload_url::$UPLOAD_URL"

    - name: Get Release ID for Tag v0.1.0
      id: get_release
      run: |
        RELEASE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/irmo-de/9UnBot/releases/tags/v0.1.0")
        RELEASE_ID=$(echo "$RELEASE_DATA" | jq -r .id)
        echo "Release ID is $RELEASE_ID"
        echo "::set-output name=release_id::$RELEASE_ID"

    - name: Upload APK to Release
      run: |
        UPLOAD_URL="https://uploads.github.com/repos/irmo-de/9UnBot/releases/${{ steps.get_release.outputs.release_id }}/assets?name=app-debug.apk"
        curl -X POST \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Content-Type: application/vnd.android.package-archive" \
             --data-binary @./app/build/outputs/apk/debug/app-debug.apk \
             "$UPLOAD_URL"
