name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  actions: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Get the latest release tag
      id: latest_release
      run: |
        LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/irmo-de/9UnBot/releases/latest")
        echo "Latest release data: $LATEST_RELEASE"
        LATEST_TAG=$(echo "$LATEST_RELEASE" | jq -r .tag_name)
        LATEST_RELEASE_ID=$(echo "$LATEST_RELEASE" | jq -r .id)
        echo "Latest release tag is $LATEST_TAG"
        echo "Latest release ID is $LATEST_RELEASE_ID"
        echo "::set-output name=tag_name::$LATEST_TAG"
        echo "::set-output name=release_id::$LATEST_RELEASE_ID"

    - name: Upload APK to the Latest Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: "https://uploads.github.com/repos/irmo-de/9UnBot/releases/${{ steps.latest_release.outputs.release_id }}/assets?name=app-debug.apk"
        asset_path: ./app/build/outputs/apk/debug/app-debug.apk
        asset_name: app-debug.apk
        asset_content_type: application/vnd.android.package-archive
